# Generated by Django 3.2.8 on 2021-10-28 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('CH', 'Coporate Headoffice'), ('OP', 'Operation Depratment'), ('WS', 'Work Station'), ('MD', 'Marketing Division')], max_length=2)),
                ('incident_department', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('incident_location', models.TextField(max_length=255)),
                ('initial_severity', models.CharField(choices=[('M', 'Mild'), ('MO', 'Moderate'), ('S', 'Severe'), ('F', 'Fatal')], max_length=2)),
                ('suspected_cause', models.TextField(max_length=255)),
                ('action_taken', models.TextField(max_length=255)),
                ('incident_types', models.CharField(choices=[('E', 'Environmental incident'), ('I', 'Injury'), ('P', 'Property damage'), ('V', 'Vehicle')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
