# Generated by Django 3.2.8 on 2021-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211029_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_info',
            name='user',
        ),
        migrations.AlterField(
            model_name='report_info',
            name='location',
            field=models.CharField(choices=[('CH', 'Coporate Headoffice'), ('OD', 'Operation Depratment'), ('WS', 'Work Station'), ('MD', 'Marketing Division')], max_length=2),
        ),
    ]
